"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const auth_middleware_1 = require("../middleware/auth.middleware");
const document_access_middleware_1 = require("../middleware/document-access.middleware");
const snapshots_controller_1 = require("./snapshots.controller");
const router = (0, express_1.Router)({ mergeParams: true });
router.use(auth_middleware_1.requireAuth);
router.post("/", (0, document_access_middleware_1.requireDocumentRole)("EDITOR"), snapshots_controller_1.create);
router.get("/", (0, document_access_middleware_1.requireDocumentRole)("VIEWER"), snapshots_controller_1.list);
router.get("/:snapshotId", (0, document_access_middleware_1.requireDocumentRole)("VIEWER"), snapshots_controller_1.getOne);
router.post("/:snapshotId/restore", (0, document_access_middleware_1.requireDocumentRole)("EDITOR"), snapshots_controller_1.restore);
exports.default = router;
